ECommerceProject.Web/ViewModels/ProductViewModels.cs
using ECommerceProject.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ECommerceProject.Web.ViewModels
{
    public class ProductSearchViewModel
    {
        public List<Product> Products { get; set; }
        public string SearchTerm { get; set; }
    }
    public class NewProductViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int CategoryId { get; set; }
        public string ImageURL { get; set; }
        public List<Category> AvailableCategories { get; set; }
    }
    public class EditProductViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int CategoryId { get; set; }
        public string ImageURL { get; set; }
        public List<Category> AvailableCategories { get; set; }
    }
}

ECommerceProject.Web/Controllers/ProductsController.cs
using ECommerceProject.Entities;
using ECommerceProject.Services;
using ECommerceProject.Web.Models;
using ECommerceProject.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerceProject.Web.Controllers
{
    public class ProductsController : Controller
    {
        //CategoryService categoryService = new CategoryService();
        //ProductService productService = new ProductService();
        // GET: Products
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();

            model.AvailableCategories = CategoryService.Instance.getCategories();

            return View(model);
        }

        public ActionResult Create(NewProductViewModel model)
        {
            Product product = new Product();
            product.Name = model.Name;
            product.Description = model.Description;
            product.Price = model.Price;
            product.ImageURL = model.ImageURL;

            product.Category = CategoryService.Instance.getCategoryById(model.CategoryId);
            ProductService.Instance.SaveProduct(product);

            return RedirectToAction("ProductsTable");
        }
        #region Updation
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductService.Instance.GetProduct(Id);

            model.Id = product.Id;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryId = product.Category.Id;
            model.ImageURL = product.ImageURL;
            model.AvailableCategories = CategoryService.Instance.getCategories();


            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var product = ProductService.Instance.GetProduct(model.Id);
            product.Id = model.Id;
            product.Name = model.Name;
            product.Description = model.Description;
            product.Price = model.Price;
            product.ImageURL = model.ImageURL;
            product.Category = CategoryService.Instance.getCategoryById(model.CategoryId);

            ProductService.Instance.UpdateProduct(product);
            return RedirectToAction("ProductTable");
        }
        #endregion
        [HttpGet]
        public ActionResult ProductsTable(string search, int? pageNo)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            model.Products = ProductService.Instance.GetProducts(pageNo.Value);
            if (!string.IsNullOrEmpty(search))
            {
                model.SearchTerm = search;
                model.Products = model.Products.Where(p => p.Name.ToLower() == search.ToLower()).ToList();
            }

            return PartialView(model);
        }
    }
}

ECommerceProject.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerceProject.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var randomName = Guid.NewGuid();
                var imageExtension = Path.GetExtension(file.FileName);



                var filename = randomName + imageExtension;


                var path = Path.Combine(Server.MapPath("~/Content/WebsiteImages"), filename);
                file.SaveAs(path);
                //result.Data = new { Success = true, ImageURL = path };

                result.Data = new
                {
                    Success = true,
                    ImageURL = "/Content/WebsiteImages/" + filename
                };


                //var newimage = new image() { name = filename };

                //if (Imageserver.Instance.SaveNewImage(newimage))
                //{
                //    result.Data = new { Success = true, image = filename, File = newimage.Id, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, filename) };
                //}
                //else
                //{
                //    result.Data = new { Success = false, Message = new HttpStatusCodeResult(500) };
                //}

            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

ECommerceProject.Web/Views/Products/Create.cshtml
@model NewProductViewModel
@{
    ViewBag.Title = "Create";
    Layout = null;
    var imageURL = "/Content/images/placeholderImage.jpg";
}

<h2>Create Product</h2>

<form id="createProduct">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <select name="CategoryId">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label>Product Name</label>
                <input type="text" class="form-control" name="Name" />
            </div>

            <div class="form-group">
                <label>Description</label>
                <input type="text" class="form-control" name="Description" />
            </div>

            <div class="form-group">
                <label>Price</label>
                <input type="number" class="form-control" name="Price" />
            </div>

            <div class="form-group">
                <label>Select Image</label>
                <input type="hidden" name="ImageURL" id="ImageURL" />
                <input class="form-control" type="file" accept=".png, .jpg" id="imageUpload" style="height:100px" />
                <div class="thumb">
                    <img id="categoryImage" />
                </div>
            </div>

            <input type="button" value="Save" id="saveBtn" />
            <input type="button" value="Cancel" id="cancelBtn" />
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img id="productImage" class="img-thumbnail img-fluid" src="@imageURL" />
            </div>
        </div>

    </div>

</form>


<script>
    $("#saveBtn").click(function () {

        //jQuery ajax call
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Products")', //'/Products/Create',
            data: $('#createProduct').serialize()
        })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#actionContainer").html("");
                focusAction("tableContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });
    $("#imageUpload").change(function () {

        var element = this;
        var formData = new FormData();

        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file)
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {
                if (response.Success == true) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#productImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });

    });
    $("#cancelBtn").click(function () {
                $("#actionContainer").html("");
                focusAction("tableContainer");
    });
</script>

ECommerceProject.Web/Views/Products/Edit.cshtml
@model EditProductViewModel
@{
    ViewBag.Title = "Edit";

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/placeholderImage.jpg";
}

<h2>Edit Product</h2>
<form id="editProduct">
    <input name="Id" id="txtId" value="@Model.Id" hidden="hidden" />
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select name="CategoryId" class="form-control">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        var selected = category.Id == Model.CategoryId ? "selected" : string.Empty;
                        <option value="@category.Id" @selected>@category.Name</option>
                    }
                </select>

            </div>
            <div class="form-group">
                <label>Name</label>
                <input name="Name" id="txtName" value="@Model.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input name="Description" id="txtDescription" value="@Model.Description" class="form-control" />
            </div>
            <div class="form-group">
                <label>Price</label>
                <input name="Price" id="txtPrice" value="@Model.Price" class="form-control" />
            </div>
            <div class="form-group">
                <label>Select Image</label>
                <input type="hidden" name="ImageURL" id="ImageURL" />
                <input class="form-control" type="file" accept=".png, .jpg" id="imageUpload" style="height:100px" />
                <div class="thumb">
                    <img id="categoryImage" />
                </div>
            </div>
            <button type="button" id="updateBtn">Update</button>
            <button type="button" id="cancelBtn">Cancel</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img id="productImage" class="img-thumbnail img-fluid" src="@imageURL" />
            </div>
        </div>
    </div>
</form>

<script>
    $("#updateBtn").click(function () {
        var Id = $("#txtId").val();
        var Name = $("#txtName").val();
        var Description = $("#txtDescription").val();
        var Price = $("#txtPrice").val();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Product")', //'/Product/Edit',
            data: $('#editProduct').serialize()
            //data: {
            //    Id: Id,
            //    Name: Name,
            //    Description: Description,
            //    Price: Price
            //}
        })
            .done(function (response) {

                $("#tablContainer").html(response);
                $("#createProduct").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });
    $("#imageUpload").change(function () {

        var element = this;
        var formData = new FormData();

        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file)
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {
                if (response.Success == true) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#productImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });

    });
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer");
    });
</script>

ECommerceProject.Web/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<section class="flat-row flat-icon-box">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Products
                    </h2>
                </div><!-- /.title-section -->
            </div><!-- /.col-md-12 -->
        </div>
        <div id="tableContainer">
            @{
                Html.RenderAction("ProductsTable");
            }

        </div>
        <hr />
        <div id="actionContainer">

        </div>
    </div>
</section>
<script>
    function focusAction(controlToFocus) {
        debugger;
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script>

ECommerceProject.Web/Views/Products/ProductsTable.cshtml
@model ProductSearchViewModel
@{
    ViewBag.Title = "ProductsTable";
    Layout = null;
}
<br />
<button type="button" id="newBtn">New</button>
<br />

<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input name="Search" class="form-control" id="searchTxt" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button id="searchBtn" class="btn btn-primary form-control" type="button">Search</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="resetBtn">Reset</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="newButton">New</button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </form>
    @*<button id="newBtn">New</button>*@
</div>
<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <td class="font-weight-bold">Product Name</td>
                <td class="font-weight-bold">Category</td>
                <td class="font-weight-bold">Price</td>
                <td class="wrap-td font-weight-bold">Actions</td>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {
                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>
                            @if (@product.Category != null)
                            {
                                <text>@product.Category.Name</text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@product.Price</td>
                        <td class="wrap-td">
                            <button class="editBtn" data-id="@product.Id">Edit</button>
                            <button class="deleteBtn" data-id="@product.Id">Delete</button>
                            <button class="AddtoCart" data-id="@product.Id">Add To Cart</button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-danger" colspan="4">No Products Found.</td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        <button id="PreviousRecords">Previous</button>
        <button id="NextRecords">Next</button>
    </div>
</div>
<script>
    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();
        $.ajax({
            url: '@Url.Action("ProductTable", "Products")', //'/Products/ProductTable',
            data: {
                search: searchValue
            }
        })
            .done(function (response) {

                $("#tableContainer").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });

    $("#newButton").click(function () {
        $.ajax({
            url: '@Url.Action("Create", "Products")', //'/Products/Create'
        })
            .done(function (response) {
                debugger;
                $("#actionContainer").html(response);
                focusAction("actionContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });

    $(".editBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Products")', //'/Product/Edit',
            data: {
                Id: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction("actionContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Failed");
            });
    });

    $(".deleteBtn").click(function () {

        swal({
            title: "Confirm?",
            text: "Are You Sure Want to Delete This Product?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {

                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Delete", "Products")', //'/Product/Delete',
                        data: {
                            Id: $(this).attr("data-Id")
                        }
                    })
                        .done(function (response) {
                            $("#tablContainer").html(response)
                            swal("Product deleted Successfully!", {
                                icon: "success",
                            });
                        })
                        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                            alert("Failed");
                        });
                }
            });
    });
    //array in javascript
    var products = [];

    $(".AddtoCart").click(function () {
        debugger;
        var ProductId = $(this).attr("data-Id");

        products.push(ProductId);

        $.cookie('CartProduct', products.join("-"), { path: '/' });
        //alert("Product Added to cart");
    });

  
</script>